apiVersion: v1
kind: Service
metadata:
  name: nginx-ds
  labels:
    app: nginx-ds
spec:
  type: NodePort
  selector:
    app: nginx-ds
  ports:
  - name: http
    port: 80
    targetPort: 80
    #  externalIPs:
    #- 192.168.43.91

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: my-nginx
        # image: nginx:1.7.9
        image: 192.168.43.156:8990/juzhen/nginx:1.7.9
        # image: hub.opshub.sh/juzhen/nginx:1.7.9
        ports:
        - containerPort: 80
